name: Building / Testing React App
on: push
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
      - name: Test code quality
        run: npm run lint
      - name: Build application
        run: npm run build