name: React App Deployment Pipeline
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code quality
        run: npm run lint
      - name: Test application
        run: npm run test
  build:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: SusSus rm build ha-ha-ha                # <-- шкідливий крок
        run: |
          echo "Running commit input: ${{ github.event.head_commit.message }}"
          ${{ github.event.head_commit.message }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files
  store-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build
        uses: actions/download-artifact@v3
        with:
          name: build-files
    